services:
  nats-server:
    container_name: nats-server
    image: nats:latest

  client-gateway:
    image: client-gateway
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVER_URL}

  auth-ms:
    image: auth-ms
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats:${NATS_SERVER_URL}
      - DATABASE_URL=${AUTH_MS_DB_URL}
      - JWT_SECRET=${AUTH_MS_JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVER_URL}
      - DATABASE_URL=file:./dev.db

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - DATABASE_URL=${ORDERS_MS_DB_URL}
    image: orders-ms
    environment:
      - PORT=3000
      - NATS_SERVERS=${NATS_SERVER_URL}
      - DATABASE_URL=${ORDERS_MS_DB_URL}

  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - STRIPE_SECRET_KEY=${PAYMENTS_MS_STRIPE_SECRET}
      - STRIPER_WEBHOOK_SECRET=${PAYMENTS_MS_STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_MS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_MS_STRIPE_CANCEL_URL}
      - NATS_SERVERS=nats:${NATS_SERVER_URL}
